// Copyright IBM Corp. 2007
[Description ("Xen_ComputerSystem created")]
class Xen_ComputerSystemCreatedIndication : CIM_InstCreation
{
};

[Description ("Xen_ComputerSystem deleted")]
class Xen_ComputerSystemDeletedIndication : CIM_InstDeletion
{
};


[Description ("KVM_ComputerSystem lifecycle")]
class KVM_ComputerSystemCreatedIndication : CIM_InstCreation
{
};

[Description ("KVM_ComputerSystem lifecycle")]
class KVM_ComputerSystemDeletedIndication : CIM_InstDeletion
{
};
