// Copyright IBM Corp. 2007

[Description ("Xen_ComputerSystem created"),
 Provider("cmpi::Virt_ComputerSystemIndication")
]
class Xen_ComputerSystemCreatedIndication : CIM_InstCreation
{
};

[Description ("Xen_ComputerSystem deleted"),
 Provider("cmpi::Virt_ComputerSystemIndication")
]
class Xen_ComputerSystemDeletedIndication : CIM_InstDeletion
{
};

[Description ("Xen_ComputerSystem modified"),
 Provider("cmpi::Virt_ComputerSystemIndication")
]
class Xen_ComputerSystemModifiedIndication : CIM_InstModification
{
};

[Description ("KVM_ComputerSystem lifecycle"),
 Provider("cmpi::Virt_ComputerSystemIndication")
]
class KVM_ComputerSystemCreatedIndication : CIM_InstCreation
{
};

[Description ("KVM_ComputerSystem lifecycle"),
 Provider("cmpi::Virt_ComputerSystemIndication")
]
class KVM_ComputerSystemDeletedIndication : CIM_InstDeletion
{
};

[Description ("KVM_ComputerSystem modified"),
 Provider("cmpi::Virt_ComputerSystemIndication")
]
class KVM_ComputerSystemModifiedIndication : CIM_InstModification
{
};

[Description ("LXC_ComputerSystem created"),
 Provider("cmpi::Virt_ComputerSystemIndication")
]
class LXC_ComputerSystemCreatedIndication : CIM_InstCreation
{
};

[Description ("LXC_ComputerSystem deleted"),
 Provider("cmpi::Virt_ComputerSystemIndication")
]
class LXC_ComputerSystemDeletedIndication : CIM_InstDeletion
{
};

[Description ("LXC_ComputerSystem modified"),
 Provider("cmpi::Virt_ComputerSystemIndication")
]
class LXC_ComputerSystemModifiedIndication : CIM_InstModification
{
};
