// Copyright IBM Corp. 2007

[Provider("cmpi::Virt_DevicePool")]
class Xen_DiskPool : CIM_ResourcePool
{
};

[Provider("cmpi::Virt_DevicePool")]
class KVM_DiskPool : CIM_ResourcePool
{
};

[Provider("cmpi::Virt_DevicePool")]
class LXC_DiskPool : CIM_ResourcePool
{
};

