// Copyright IBM Corp. 2007

[Association,
 Provider("cmpi::Virt_ElementSettingData")
]
class Xen_ElementSettingData : CIM_ElementSettingData
{
};

[Association,
 Provider("cmpi::Virt_ElementSettingData")
]
class KVM_ElementSettingData : CIM_ElementSettingData
{
};

[Association,
 Provider("cmpi::Virt_ElementSettingData")
]
class LXC_ElementSettingData : CIM_ElementSettingData
{
};
