// Copyright 2007 IBM. All rights reserved.

// ==================================================================
// Xen_ElementConformsToProfile
// ==================================================================
[Association,
 Description (
        "A class to associate a ManagedElement with its RegisteredProfile."
)]
class Xen_ElementConformsToProfile : CIM_ElementConformsToProfile
{
};

// ==================================================================
// KVM_ElementConformsToProfile
// ==================================================================
[Association,
 Description (
        "A class to associate a ManagedElement with its RegisteredProfile."
)]
class KVM_ElementConformsToProfile : CIM_ElementConformsToProfile
{
};

