// Copyright IBM Corp. 2007

[Association,
 Description (
        "A class to associate a ManagedElement with its RegisteredProfile."),
 Provider("cmpi::Virt_ElementConformsToProfile")
]
class Xen_ElementConformsToProfile : CIM_ElementConformsToProfile
{

  [Override ("ConformantStandard")]
  Xen_RegisteredProfile REF ConformantStandard;

};

[Association,
 Description (
        "A class to associate a ManagedElement with its RegisteredProfile."),
 Provider("cmpi::Virt_ElementConformsToProfile")
]
class KVM_ElementConformsToProfile : CIM_ElementConformsToProfile
{

  [Override ("ConformantStandard")]
  KVM_RegisteredProfile REF ConformantStandard;

};

[Association,
 Description (
        "A class to associate a ManagedElement with its RegisteredProfile."),
 Provider("cmpi::Virt_ElementConformsToProfile")
]
class LXC_ElementConformsToProfile : CIM_ElementConformsToProfile
{

  [Override ("ConformantStandard")]
  LXC_RegisteredProfile REF ConformantStandard;

};
