// Copyright IBM Corp. 2007

[Association,
 Description (
        "A class to associate a ManagedElement with its RegisteredProfile.")
]
class Xen_ElementConformsToProfile : CIM_ElementConformsToProfile
{

  [Override ("ConformantStandard")]
  Xen_RegisteredProfile REF ConformantStandard;

};

[Association,
 Description (
        "A class to associate a ManagedElement with its RegisteredProfile.")
]
class KVM_ElementConformsToProfile : CIM_ElementConformsToProfile
{

  [Override ("ConformantStandard")]
  KVM_RegisteredProfile REF ConformantStandard;

};

