// Copyright IBM Corp. 2007

[Association,
 Provider("cmpi::Virt_HostedService")
]
class Xen_HostedService : CIM_HostedService
{
};

[Association,
 Provider("cmpi::Virt_HostedService")
]
class KVM_HostedService : CIM_HostedService
{
};

[Association,
 Provider("cmpi::Virt_HostedService")
]
class LXC_HostedService : CIM_HostedService
{
};
