// Copyright IBM Corp. 2007

[Description (
	"A class derived from CIM_ComputerSystem to represent "
	"the Xen host system."),
 Provider("cmpi::Virt_HostSystem")
]
class Xen_HostSystem : CIM_ComputerSystem
{
};

[Description (
	"A class derived from CIM_ComputerSystem to represent "
	"the KVM host system."),
 Provider("cmpi::Virt_HostSystem")
]
class KVM_HostSystem : CIM_ComputerSystem
{
};

[Description (
	"A class derived from CIM_ComputerSystem to represent "
	"the LXC host system."),
 Provider("cmpi::Virt_HostSystem")
]
class LXC_HostSystem : CIM_ComputerSystem
{
};
