// Copyright 2007 IBM. All rights reserved.

// ==================================================================
// Xen_LogicalDisk
// ==================================================================
[Description (
	"A class derived from CIM_LogicalDisk to represent "
	"the Xen virtual disks on the system.")]
class Xen_LogicalDisk : CIM_LogicalDisk
{
};

// Copyright 2007 IBM. All rights reserved.

// ==================================================================
// KVM_LogicalDisk
// ==================================================================
[Description (
	"A class derived from CIM_LogicalDisk to represent "
	"the KVM virtual disks on the system.")]
class KVM_LogicalDisk : CIM_LogicalDisk
{
};

