// Copyright IBM Corp. 2007

[Description (
        "A class derived from CIM_Memory to represent "
        "the Xen virtual memory."),
 Provider("cmpi::Virt_Device")
]
class Xen_Memory : CIM_Memory
{
};

[Description (
        "A class derived from CIM_Memory to represent "
        "the KVM virtual memory."),
 Provider("cmpi::Virt_Device")
]
class KVM_Memory : CIM_Memory
{
};

[Description (
        "A class derived from CIM_Memory to represent "
        "the KVM virtual memory."),
 Provider("cmpi::Virt_Device")
]
class LXC_Memory : CIM_Memory
{
};
