// Copyright 2007 IBM. All rights reserved.

// ==================================================================
// Xen_MemoryPool
// ==================================================================
class Xen_MemoryPool : CIM_ResourcePool
{
};

// Copyright 2007 IBM. All rights reserved.

// ==================================================================
// KVM_MemoryPool
// ==================================================================
class KVM_MemoryPool : CIM_ResourcePool
{
};

