// Copyright IBM Corp. 2007

[Description (
	"A class derived from CIM_NetworkPort to represent "
	"the Xen virtual network interfaces on the system."),
 Provider("cmpi::Virt_Device")
]
class Xen_NetworkPort : CIM_NetworkPort
{
};

[Description (
	"A class derived from CIM_NetworkPort to represent "
	"the KVM virtual network interfaces on the system."),
 Provider("cmpi::Virt_Device")
]
class KVM_NetworkPort : CIM_NetworkPort
{
};

[Description (
	"A class derived from CIM_NetworkPort to represent "
	"the LXC virtual network interfaces on the system."),
 Provider("cmpi::Virt_Device")
]
class LXC_NetworkPort : CIM_NetworkPort
{
};
