// Copyright IBM Corp. 2007

[Description (
	"A class derived from CIM_NetworkPort to represent "
	"the Xen virtual network interfaces on the system.")
]
class Xen_NetworkPort : CIM_NetworkPort
{
};

[Description (
	"A class derived from CIM_NetworkPort to represent "
	"the KVM virtual network interfaces on the system.")
]
class KVM_NetworkPort : CIM_NetworkPort
{
};

