// Copyright IBM Corp. 2007

[Description (
	"A class derived from CIM_Processor to represent "
	"the Xen virtual processors.")
]
class Xen_Processor : CIM_Processor
{
};

[Description (
	"A class derived from CIM_Processor to represent "
	"the KVM virtual processors.")
]
class KVM_Processor : CIM_Processor
{
};

