// Copyright IBM Corp. 2007

[Provider("cmpi::Virt_DevicePool")]
class Xen_ProcessorPool : CIM_ResourcePool
{
};

[Provider("cmpi::Virt_DevicePool")]
class KVM_ProcessorPool : CIM_ResourcePool
{
};

[Provider("cmpi::Virt_DevicePool")]
class LXC_ProcessorPool : CIM_ResourcePool
{
};
