// Copyright IBM Corp. 2007

[Description (
	"A class derived from CIM_Processor to represent "
	"the Xen virtual processors."),
 Provider("cmpi::Virt_Device")
]
class Xen_Processor : CIM_Processor
{
};

[Description (
	"A class derived from CIM_Processor to represent "
	"the KVM virtual processors."),
 Provider("cmpi::Virt_Device")
]
class KVM_Processor : CIM_Processor
{
};

[Description (
	"A class derived from CIM_Processor to represent "
	"the LXC virtual processors."),
 Provider("cmpi::Virt_Device")
]
class LXC_Processor : CIM_Processor
{
};
