// Copyright IBM Corp. 2007

[Description (
	"A class derived from CIM_RegisteredProfile to represent "
	"an advertised conformant profile.")
]
class Xen_RegisteredProfile : CIM_RegisteredProfile
{
};

[Description (
	"A class derived from CIM_RegisteredProfile to represent "
	"an advertised conformant profile.")
]
class KVM_RegisteredProfile : CIM_RegisteredProfile
{
};

