// Copyright IBM Corp. 2007

[Association]
class Xen_ResourceAllocationFromPool : CIM_ResourceAllocationFromPool
{
};

[Association]
class KVM_ResourceAllocationFromPool : CIM_ResourceAllocationFromPool
{
};
