// Copyright IBM Corp. 2007

class Xen_ResourceAllocationSettingData : CIM_ResourceAllocationSettingData
{
};

class KVM_ResourceAllocationSettingData : CIM_ResourceAllocationSettingData
{
};

class LXC_ResourceAllocationSettingData : CIM_ResourceAllocationSettingData
{
};

[Description ("Xen virtual disk configuration"),
 Provider("cmpi::Virt_RASD")
]
class Xen_DiskResourceAllocationSettingData : Xen_ResourceAllocationSettingData
{

      [Description ("Device as seen by the guest")]
      string VirtualDevice;

      [Description ("Device emulation type"),
        ValueMap {"0", "1"},
        Values {"Disk", "CDROM"}]
      uint16 EmulatedType;
};

[Description ("KVM virtual disk configuration"),
 Provider("cmpi::Virt_RASD")
]
class KVM_DiskResourceAllocationSettingData : KVM_ResourceAllocationSettingData
{

      [Description ("Device as seen by the guest")]
      string VirtualDevice;

      [Description ("Device emulation type"),
        ValueMap {"0", "1"},
        Values {"Disk", "CDROM"}]
      uint16 EmulatedType;
};

[Description ("LXC virtual disk configuration"),
 Provider("cmpi::Virt_RASD")
]
class LXC_DiskResourceAllocationSettingData : LXC_ResourceAllocationSettingData
{

      [Description ("Mount point within the container")]
      string MountPoint;

};

[Description ("Xen virtual network configuration"),
 Provider("cmpi::Virt_RASD")
]
class Xen_NetResourceAllocationSettingData : Xen_ResourceAllocationSettingData
{

      [Description ("Interface type")]
      string NetworkType;

};

[Description ("KVM virtual network configuration"),
 Provider("cmpi::Virt_RASD")
]
class KVM_NetResourceAllocationSettingData : KVM_ResourceAllocationSettingData
{

      [Description ("Interface type")]
      string NetworkType;

};

[Description ("LXC virtual network configuration"),
 Provider("cmpi::Virt_RASD")
]
class LXC_NetResourceAllocationSettingData : LXC_ResourceAllocationSettingData
{
};

[Description ("Xen virtual processor"),
 Provider("cmpi::Virt_RASD")
]
class Xen_ProcResourceAllocationSettingData : Xen_ResourceAllocationSettingData
{
};

[Description ("KVM virtual processor"),
 Provider("cmpi::Virt_RASD")
]
class KVM_ProcResourceAllocationSettingData : KVM_ResourceAllocationSettingData
{
};

[Description ("LXC virtual processor"),
 Provider("cmpi::Virt_RASD")
]
class LXC_ProcResourceAllocationSettingData : LXC_ResourceAllocationSettingData
{
};

[Description ("Xen virtual memory"),
 Provider("cmpi::Virt_RASD")
]
class Xen_MemResourceAllocationSettingData : Xen_ResourceAllocationSettingData
{
};

[Description ("KVM virtual memory"),
 Provider("cmpi::Virt_RASD")
]
class KVM_MemResourceAllocationSettingData : KVM_ResourceAllocationSettingData
{
};

[Description ("LXC virtual memory"),
 Provider("cmpi::Virt_RASD")
]
class LXC_MemResourceAllocationSettingData : LXC_ResourceAllocationSettingData
{
};

[Description ("Xen virtual graphics device"),
 Provider("cmpi::Virt_RASD")
]
class Xen_GraphicsResourceAllocationSettingData : Xen_ResourceAllocationSettingData
{
};

[Description ("KVM virtual graphics device"),
 Provider("cmpi::Virt_RASD")
]
class KVM_GraphicsResourceAllocationSettingData : KVM_ResourceAllocationSettingData
{
};

[Description ("LXC virtual graphics device"),
 Provider("cmpi::Virt_RASD")
]
class LXC_GraphicsResourceAllocationSettingData : LXC_ResourceAllocationSettingData
{
};

[Description ("Xen virtual input device"),
 Provider("cmpi::Virt_RASD")
]
class Xen_InputResourceAllocationSettingData : Xen_ResourceAllocationSettingData
{
};

[Description ("KVM virtual input device"),
 Provider("cmpi::Virt_RASD")
]
class KVM_InputResourceAllocationSettingData : KVM_ResourceAllocationSettingData
{
};

[Description ("LXC virtual input device"),
 Provider("cmpi::Virt_RASD")
]
class LXC_InputResourceAllocationSettingData : LXC_ResourceAllocationSettingData
{
};

