// Copyright IBM Corp. 2007

[Association,
 Provider("cmpi::Virt_ResourceAllocationFromPool")
]
class Xen_ResourceAllocationFromPool : CIM_ResourceAllocationFromPool
{
};

[Association,
 Provider("cmpi::Virt_ResourceAllocationFromPool")
]
class KVM_ResourceAllocationFromPool : CIM_ResourceAllocationFromPool
{
};

[Association,
 Provider("cmpi::Virt_ResourceAllocationFromPool")
]
class LXC_ResourceAllocationFromPool : CIM_ResourceAllocationFromPool
{
};
