// Copyright IBM Corp. 2007
class Xen_ResourcePoolConfigurationService : CIM_ResourcePoolConfigurationService {

};

class KVM_ResourcePoolConfigurationService : CIM_ResourcePoolConfigurationService {

};