// Copyright IBM Corp. 2007

[Association]
class Xen_SettingsDefineCapabilities : CIM_SettingsDefineCapabilities
{
};

[Association]
class KVM_SettingsDefineCapabilities : CIM_SettingsDefineCapabilities
{
};

