// Copyright IBM Corp. 2007

[Association,
 Provider("cmpi::Virt_SettingsDefineState")
]
class Xen_SettingsDefineState : CIM_SettingsDefineState
{
};

[Association,
 Provider("cmpi::Virt_SettingsDefineState")
]
class KVM_SettingsDefineState : CIM_SettingsDefineState
{
};