// Copyright IBM Corp. 2008

class Xen_VirtualSystemSnapshotService : Virt_VirtualSystemSnapshotService { };
class KVM_VirtualSystemSnapshotService : Virt_VirtualSystemSnapshotService { };
class LXC_VirtualSystemSnapshotService : Virt_VirtualSystemSnapshotService { };
