// Copyright IBM Corp. 2007

[Description (
	"A class derived from CIM_Capabilities to represent "
	"the management capabilities of a Xen virtual system")
]
class Xen_VirtualSystemManagementCapabilities : CIM_VirtualSystemManagementCapabilities
{
};

[Description (
	"A class derived from CIM_Capabilities to represent "
	"the management capabilities of a KVM virtual system.")
]
class KVM_VirtualSystemManagementCapabilities : CIM_VirtualSystemManagementCapabilities
{
};

