// Copyright IBM Corp. 2008

class Xen_VirtualSystemSnapshotService : CIM_VirtualSystemSnapshotService { };
class KVM_VirtualSystemSnapshotService : CIM_VirtualSystemSnapshotService { };
class LXC_VirtualSystemSnapshotService : CIM_VirtualSystemSnapshotService { };
