// Copyright IBM Corp. 2007

class CIM_VirtualSystemMigrationSettingData : CIM_SettingData {
      uint16 MigrationType;

      uint16 Priority;
};

[Provider("cmpi::Virt_VSMigrationSettingData")]
class Xen_VirtualSystemMigrationSettingData : CIM_VirtualSystemMigrationSettingData {
    [ ValueMap {"0","1","2","3","4","5","6"},
      Values { "Unknown", "Other", "SSH", "TLS", "TLS Strict", "TCP", "UNIX" }]
    uint16 TransportType;
    string CheckParameters[];
};

[Provider("cmpi::Virt_VSMigrationSettingData")]
class KVM_VirtualSystemMigrationSettingData : CIM_VirtualSystemMigrationSettingData {
    [ ValueMap {"0","1","2","3","4","5","6"},
      Values { "Unknown", "Other", "SSH", "TLS", "TLS Strict", "TCP", "UNIX" }]
    uint16 TransportType;
    string CheckParameters[];
};
