// Copyright IBM Corp. 2007

class Virt_VirtualSystemMigrationCapabilities : CIM_Capabilities {

  uint16 DestinationHostFormatsSupported[];

  uint16 SynchronousMethodsSupported[];

  uint16 AsynchronousMethodsSupported[];

};

[Provider("cmpi::Virt_VSMigrationCapabilities")]
class Xen_VirtualSystemMigrationCapabilities : Virt_VirtualSystemMigrationCapabilities {
};

[Provider("cmpi::Virt_VSMigrationCapabilities")]
class KVM_VirtualSystemMigrationCapabilities : Virt_VirtualSystemMigrationCapabilities {
};
