// Copyright IBM Corp. 2007

// Placeholder definition until schema is available upstream

class CIM_VirtualSystemMigrationService : CIM_Service {
      uint32 VirtualSystemIsMigratableToHost(
      	     [Out]
	       CIM_ConcreteJob REF Job,
	     [In, EmbeddedInstance("CIM_ResourceAllocationSettingData")]
	       string NewResourceSettingData[],
	     [In, EmbeddedInstance("CIM_SettingData")]
	       string MigrationSettingData,
	     [In, EmbeddedInstance("CIM_VirtualSystemSettingData")]
 	       string NewSystemSettingData,
	     [In]
	       CIM_ComputerSystem REF ComputerSystem,
	     [In]
	       string DestinationHost);

      uint32 MigrateVirtualSystemToHost(
      	     [Out]
	       CIM_ConcreteJob REF Job,
	     [In, EmbeddedInstance("CIM_ResourceAllocationSettingData")]
	       string NewResourceSettingData[],
	     [In, EmbeddedInstance("CIM_SettingData")]
	       string MigrationSettingData,
	     [In, EmbeddedInstance("CIM_VirtualSystemSettingData")]
 	       string NewSystemSettingData,
	     [In]
	       CIM_ComputerSystem REF ComputerSystem,
	     [In]
	       string DestinationHost);

};

class Virt_MigrationJob : CIM_ConcreteJob {
};

[Provider("cmpi::Virt_VSMigrationService")]
class Xen_VirtualSystemMigrationService : CIM_VirtualSystemMigrationService {
};

[Provider("cmpi::Virt_VSMigrationService")]
class KVM_VirtualSystemMigrationService : CIM_VirtualSystemMigrationService {
};

