// Copyright IBM Corp. 2007

// Placeholder definition until schema is available upstream

class CIM_VirtualSystemMigrationService : CIM_Service {
      uint32 CheckVirtualSystemIsMigratableToHost(
	     [In]
	       CIM_ComputerSystem REF ComputerSystem,
	     [In]
	       string DestinationHost,
	     [In, EmbeddedInstance("CIM_SettingData")]
	       string MigrationSettingData,
	     [In, EmbeddedInstance("CIM_VirtualSystemSettingData")]
 	       string NewSystemSettingData,
	     [In, EmbeddedInstance("CIM_ResourceAllocationSettingData")]
	       string NewResourceSettingData[],
	     [Out]
	       boolean IsMigratable
      );

      uint32 CheckVirtualSystemIsMigratableToSystem(
	     [In]
	       CIM_ComputerSystem REF ComputerSystem,
	     [In]
	       CIM_System REF DestinationSystem,
	     [In, EmbeddedInstance("CIM_SettingData")]
	       string MigrationSettingData,
	     [In, EmbeddedInstance("CIM_VirtualSystemSettingData")]
 	       string NewSystemSettingData,
	     [In, EmbeddedInstance("CIM_ResourceAllocationSettingData")]
	       string NewResourceSettingData[],
	     [Out]
	       boolean IsMigratable
      );


      uint32 MigrateVirtualSystemToHost(
	     [In]
	       CIM_ComputerSystem REF ComputerSystem,
	     [In]
	       string DestinationHost,
	     [In, EmbeddedInstance("CIM_SettingData")]
	       string MigrationSettingData,
	     [In, EmbeddedInstance("CIM_VirtualSystemSettingData")]
 	       string NewSystemSettingData,
	     [In, EmbeddedInstance("CIM_ResourceAllocationSettingData")]
	       string NewResourceSettingData[],
      	     [Out]
	       CIM_ConcreteJob REF Job
      );

      uint32 MigrateVirtualSystemToSystem(
	     [In]
	       CIM_ComputerSystem REF ComputerSystem,
	     [In]
	       CIM_System REF DestinationSystem,
	     [In, EmbeddedInstance("CIM_SettingData")]
	       string MigrationSettingData,
	     [In, EmbeddedInstance("CIM_VirtualSystemSettingData")]
 	       string NewSystemSettingData,
	     [In, EmbeddedInstance("CIM_ResourceAllocationSettingData")]
	       string NewResourceSettingData[],
      	     [Out]
	       CIM_ConcreteJob REF Job
      );
};

class Xen_MigrationJob : CIM_ConcreteJob {
};

class KVM_MigrationJob : CIM_ConcreteJob {
};

[Provider("cmpi::Virt_VSMigrationService")]
class Xen_VirtualSystemMigrationService : CIM_VirtualSystemMigrationService {
};

[Provider("cmpi::Virt_VSMigrationService")]
class KVM_VirtualSystemMigrationService : CIM_VirtualSystemMigrationService {
};

[Provider("cmpi::Virt_VSMigrationService")]
class LXC_VirtualSystemMigrationService : CIM_VirtualSystemMigrationService {
};

