// Copyright IBM Corp. 2007

[Association,
 Provider("cmpi::Virt_VSSDComponent")
]
class Xen_VirtualSystemSettingDataComponent : CIM_Component
{
};

[Association,
 Provider("cmpi::Virt_VSSDComponent")
]
class KVM_VirtualSystemSettingDataComponent : CIM_Component
{
};
